dbt_project_02:
  outputs:
    dev:
      account: YPDXYLS-NC25656
      database: ELIMA_DEV
      password: Ph@2695902
      role: ACCOUNTADMIN
      schema: RAW
      threads: 1
      type: snowflake
      user: PAULOHNERI
      warehouse: COMPUTE_WH 
  prd:
      account: YPDXYLS-NC25656
      database: ELIMA_PRD
      password: Ph@2695902
      role: ACCOUNTADMIN
      schema: RAW
      threads: 1
      type: snowflake
      user: PAULOHNERI
      warehouse: COMPUTE_WH
  target: dev
